name: build

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        echo $GPG_SIGNING_KEY | base64 --decode | gpg --import --no-tty --batch --yes
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Run Maven Verify Phase
      run: mvn -B verify -P sign --file pom.xml
      env:
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
