name: ci

on: push

jobs:
  compile-test-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Clean
      run: mvn clean

    - name: Compile
      run: mvn compile

    - name: Run Tests
      run: mvn test

    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        echo $GPG_SIGNING_KEY | base64 --decode | gpg --import --no-tty --batch --yes
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    - name: Configure Maven Settings
      run: |
        echo $MAVEN_SETTINGS > ~/.m2/settings.xml
      env:
        MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

    - name: Configure git
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Prepare Release
      run: mvn -P sign --batch-mode release:prepare -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Perform Release
      run: mvn -P sign --batch-mode release:perform
      env:
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
