name: release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Git Config
      run: |
        git config --global user.email "opensource@smaato.com"
        git config --global user.name "development"

    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg/
        echo $GPG_SIGNING_KEY | base64 --decode | gpg --import --no-tty --batch --yes
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    - name: Configure Maven Settings
      run: |
        echo $MAVEN_SETTINGS > ~/.m2/settings.xml
      env:
        MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

    - name: Release
      run: mvn -P sign release:prepare release:perform -B
      env:
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
